<?php
 include 'head.php';
?>

<style>
	/* carrer accordian */
	.careers-accordion {
		background-color: white;
		color: #000;
		cursor: pointer;
		padding: 5px;
		width: 100%;
		text-align: left;
		border: none;
		outline: none;
		transition: background-color 0.3s ease;
		font-size: 18px;
		font-weight: bold;
		display: flex;
		/* Added */
		align-items: center;
		/* Added */
		justify-content: space-between;
		/* Added */
	}

	.careers-accordion:hover {
		background-color: #001055;
		color: #fff;
	}

	.panel {
		padding: 0 18px;
		display: none;
		overflow: hidden;
		border-top: 1px solid #ddd;
		/* Added */
		overflow-y: auto;
		max-height:100%!important;
	}

	.panel p {
		margin-top: 20px;
	}

	.panel.active {
		display: block;
	}

	.icon {
		font-size: 35px;
		font-weight: 400;
		margin-left: 5px;
	}

	/* Add style for the horizontal line */
	.horizontal-line {
		border-top: 1px solid #4f4f4f;
		margin: 0;
	}

	/* Added class for clicked state */
	.clicked {
		background-color: #001055;
		color: #fff;
	}

	.text-color {
		color: #212529;
		line-height: 18px;
		font-size: 12px;
		font-weight: 400;
		text-align: justify;
	}

h3{
margin:0 0 2px 0;	
}

.font-body {
  font-size:22px;
  color:#001055;
  font-weight: 700;
}

p {
  margin-bottom:15px!important; 
}


.fa-solid.fa-file-pdf:hover {
color: #001055;
justify-content:center;
}
.centered-icon {
    text-align: center;
}
.text-middle{
    color:#001055;
    text-transform: capitalize; 
    font-weight:700!important;
	font-size:2.4vmax;
    margin:0 0 10px 0;
    text-align: center;
}

.vh-75 {
    height: 0vh !important;
}

.team-title h4{
    font-size:16px;
    font-family:'poppins'!important;
    text-align:center;
}

.team-title h4 span{
    font-size:12px;
    font-family:'poppins'!important;
    text-align:center;
}
</style>

<?php
 include 'sidebar/institutional_values_sidebar.php';
?>


        <div class="col-12 col-md-9 mt-3 mt-sm-0 pt-5">

          <div class="row mx-0">
            <h2 class=" text-center" style="color:#001055;
                                    text-transform: capitalize;
                                    font-weight:700!important; font-size:2.4vmax">Environmental Consciousness and <span
                class="d-block d-sm-inline">Sustainability</span></h2>
            <div class="container mb-5 mt-5">
    <hr class="horizontal-line">

    <button class="careers-accordion"> Solar Energy<span class="icon">+</span></button>
            <div class="panel active">
            <p>The UP Power Corporation has sanctioned the load of 3000 KVA & terminate the supply in meter room of 11 KV switch gear system from there University receive the supply at own 11/0.4 substation. Thesolar PV power plant of capacity 1345 KWP has been installed on the roof tops of the various buildings. The average power requirement of the campus is approximately 14000 units per day & 4500 units are generated by solar power panels i.e. approximately 31% power requirement is fulfilled by solar panels, apart from that sensor based solar street lights are installed in the campus at major places.</p>
                        <table class="table table-bordered table-striped">
                        <thead>
                        <th>#</th>
                        <th>Solar Location</th>
                        <th>Solar Capacity (In KW)</th>
                        </thead>
                        <tbody>
                        <tr>
      <td>1</td>
      <td>Dental College</td>
      <td>50</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Engineering Block</td>
      <td>50</td>
    </tr>
    <tr>
      <td>3</td>
      <td>Mala Bhawan</td>
      <td>80</td>
    </tr>
    <tr>
      <td>4</td>
      <td>Medical College</td>
      <td>110</td>
    </tr>
    <tr>
      <td>5</td>
      <td>Prakash Bhawan</td>
      <td>60</td>
    </tr>
    <tr>
      <td>6</td>
      <td>Pharmacy College</td>
      <td>30</td>
    </tr>
    <tr>
      <td>7</td>
      <td>Gyan Bhawan</td>
      <td>30</td>
    </tr>
    <tr>
      <td>8</td>
      <td>Hospital</td>
      <td>195</td>
    </tr>
    <tr>
      <td>9</td>
      <td>Indoor Stadium</td>
      <td>60</td>
    </tr>
    <tr>
      <td>10</td>
      <td>Nursing College</td>
      <td>60</td>
    </tr>
    <tr>
      <td>11</td>
      <td>Vidya Bhawan</td>
      <td>50</td>
    </tr>
    <tr>
      <td>12</td>
      <td>Vardhaman Bhawan</td>
      <td>87</td>
    </tr>
    <tr>
      <td>13</td>
      <td>Engineering Block</td>
      <td>227</td>
    </tr>
    <tr>
      <td>14</td>
      <td>Substation No-3</td>
      <td>27</td>
    </tr>
    <tr>
      <td>15</td>
      <td>Mortuary</td>
      <td>17</td>
    </tr>
    <tr>
      <td>16</td>
      <td>Faculty Block</td>
      <td>82</td>
    </tr>
    <tr>
      <td>17</td>
      <td>Faculty of Education</td>
      <td>130</td>
    </tr>
    <tr style="text-align: center;">
      <td colspan="2"><strong>Total</strong></td>
      <td><strong>1345</strong></td>
    </tr>
                        </tbody>
                      </table>
<div class="row justify-content-center gutter-30 col-mb-5">
        <div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s1.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Dental College Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s8.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer Hospital Roof</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s14.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Sub-Station No.3 Roof</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s2.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Engineering Block-I Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s9.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Indoor Stadium Roof</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s16.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Morchary 3 Roof</span></div>
    </div>
  </div>
</div>


<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s3.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Mala Bhawan Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s10.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> College of Nursing Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s16.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Faculty Block Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s4.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Medical College & Research Centre Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s12.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Vardhaman Bhawan Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s17.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Gyan Bhawan Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s5.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i>Prakash Bhawan Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s13.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Engineering Block-II Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s18.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Vidya Bhawan Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s6.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Pharmacy Block Roof </span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s19.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Solar Panels</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Faculty of Education Block Roof </span></div>
    </div>
  </div>
</div>
                    </div>
        </div>    
    <!-- Add the horizontal line here -->
    <hr class="horizontal-line">

    <button class="careers-accordion"> Biogas Plant<span class="icon">+</span></button>
        <div class="panel">
                    <div class="row justify-content-center gutter-30 col-mb-5">
    <div class="col-sm-8 col-md-8">
		<p>The University has signed MoU with JARDS Moradabad, where biogas plant is situated. The students regularly visitthe plants for the exposer purpose.</p>
    </div>    
        <div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/bio_gas.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>BioGas Plant </h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Campus</span></div>
    </div>
  </div>
</div>
    </div>         
 
    </div>
    <hr class="horizontal-line">

    <button class="careers-accordion"> Wheeling to the Grid<span class="icon">+</span></button>
    <div class="panel">
	<p>An <a href="https://www.tmu.ac.in/pdf/mous/wheeling_to_grid.pdf"> agreement</a> has been signed with Uttar Pradesh Power Corporation Limited (UPPCL) in regard with energy export to the grid and they provided net metering system to record the solar energy generation in campus.</p>
    </div>
    <hr class="horizontal-line">

    <button class="careers-accordion">Sensor-based Energy Conservation  <span class="icon">+</span></button>
        <div class="panel">
        <p>TThe University has installed sensor based & wireless facility of conserve the energy at administrative block.</p>
        <div class="row justify-content-center gutter-30 col-mb-5">
        <div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored1.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Sensor based Automatic Water Control System</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Ground Floor, Medical College & Research Centre</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored2.jpg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Sensor Based Energy Conservation </h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Indoor Stadium, Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="	https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored5.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Sensor Based Automatic Street Light System</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored3.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Sensor Based Energy Conservation Room</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Administrative Block, Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

<div class="col-sm-4 col-md-4">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored4.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Sensor Based Automatic Street Light System</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

    </div>
    </div>
	<hr class="horizontal-line">

<button class="careers-accordion"> Use of LED Bulbs / Power-efficient Equipment<span class="icon">+</span></button>
	<div class="panel">
	<p>The University purchases only LED lights &replaced old tube light/ bulb from new LED lights as and when required presently 95% of the lights are LED. The updated &power saver equipmentlike fan, AC, fridge & other electronic items are replaced by five star rated equipment.</p>
        <div class="row justify-content-center gutter-30 col-mb-5">
        <div class="col-sm-6 col-md-6">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/led.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Uses of LED Bulbs</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-6">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/5_star/ac_1.jpeg" alt="">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>Uses of Power Efficient Equipments</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-6">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/led1.jpg" alt="" style="height:400px!important;">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>LED Street Light</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>

<div class="col-sm-6 col-md-6">
  <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
    <div class="team-image">
      <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/led2.jpg" alt="" style="height:400px!important;">
    </div>
    <div class="team-desc p-2">
      <div class="team-title pt-0"><h4>LED Street Light</h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span></div>
    </div>
  </div>
</div>


    </div>
	<div class="row justify-content-center gutter-30 col-mb-5">
	<div class="col-sm-4 col-md-4">
<div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
<div class="team-image">
  <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/bio_gas.jpeg" alt="">
</div>
<div class="team-desc p-2">
  <div class="team-title pt-0"><h4>BioGas Plant </h4><span class="fst-normal" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Campus</span></div>
</div>
</div>
</div>
</div>         

</div>
<hr class="horizontal-line">


    </div>
  </div>

                </div>
              </div>

             
          </div>
        </div>
      </div>
    </div>
</section><!-- #content end -->

	<br /><br />
<script>
        //   career accordian
	var acc = document.getElementsByClassName("careers-accordion");
	var i;

	for (i = 0; i < acc.length; i++) {
		acc[i].addEventListener("click", function () {
			var panel = this.nextElementSibling;
			if (panel.style.display === "block") {
				panel.style.display = "none";
				this.querySelector(".icon").innerHTML = "+";
				this.classList.remove("clicked"); // Remove clicked class when closing
			} else {
				// Close all other panels
				var allPanels = document.querySelectorAll('.panel');
				for (var j = 0; j < allPanels.length; j++) {
					allPanels[j].style.display = 'none';
					var accordion = allPanels[j].previousElementSibling;
					accordion.querySelector(".icon").innerHTML = "+";
					accordion.classList.remove("clicked"); // Remove clicked class from other accordions
				}
				panel.style.display = "block";
				this.querySelector(".icon").innerHTML = "-";
				this.classList.add("clicked"); // Add clicked class when opening
			}
		});
	}
    </script>
	
<?php
 include 'footer.php';
?>
