<?php
include 'head.php';
?>

<section id="content">
  <div class="content-wrap py-0">
    <div class="container-fluid my-0  px-0 px-md-3">
      <div class="row">

        <?php
        include 'sidebar/institutional_values_sidebar.php';
        ?>
        <div class="col-12 col-md-10 mt-3 mt-sm-0 pt-5">
          <div class="row mx-0">
          <h1 class="tmu-text-primary tmu-page-heading"><span> Environmental Consciousness and </span><span> Sustainability</span></h1>
            <div class="container mb-3 mt-3">
              <hr class="horizontal-line">

              <button class="careers-accordion"> Solar Energy<span class="icon">+</span></button>
              <div class="panel active">
                <p>The UP Power Corporation has sanctioned the load of 3000 KVA & terminate the supply in meter room of 11 KV switch gear system from there University receive the supply at own 11/0.4 substation. Thesolar PV power plant of capacity 1345 KWP has been installed on the roof tops of the various buildings. The average power requirement of the campus is approximately 14000 units per day & 4500 units are generated by solar power panels i.e. approximately 31% power requirement is fulfilled by solar panels, apart from that sensor based solar street lights are installed in the campus at major places.</p>
                <table class="table table-bordered table-striped">
                  <thead>
                    <th>#</th>
                    <th>Solar Location</th>
                    <th>Solar Capacity (In KW)</th>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>Dental College</td>
                      <td>50</td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>Engineering Block</td>
                      <td>50</td>
                    </tr>
                    <tr>
                      <td>3</td>
                      <td>Mala Bhawan</td>
                      <td>80</td>
                    </tr>
                    <tr>
                      <td>4</td>
                      <td>Medical College</td>
                      <td>110</td>
                    </tr>
                    <tr>
                      <td>5</td>
                      <td>Prakash Bhawan</td>
                      <td>60</td>
                    </tr>
                    <tr>
                      <td>6</td>
                      <td>Pharmacy College</td>
                      <td>30</td>
                    </tr>
                    <tr>
                      <td>7</td>
                      <td>Gyan Bhawan</td>
                      <td>30</td>
                    </tr>
                    <tr>
                      <td>8</td>
                      <td>Hospital</td>
                      <td>195</td>
                    </tr>
                    <tr>
                      <td>9</td>
                      <td>Indoor Stadium</td>
                      <td>60</td>
                    </tr>
                    <tr>
                      <td>10</td>
                      <td>Nursing College</td>
                      <td>60</td>
                    </tr>
                    <tr>
                      <td>11</td>
                      <td>Vidya Bhawan</td>
                      <td>50</td>
                    </tr>
                    <tr>
                      <td>12</td>
                      <td>Vardhaman Bhawan</td>
                      <td>87</td>
                    </tr>
                    <tr>
                      <td>13</td>
                      <td>Engineering Block</td>
                      <td>227</td>
                    </tr>
                    <tr>
                      <td>14</td>
                      <td>Substation No-3</td>
                      <td>27</td>
                    </tr>
                    <tr>
                      <td>15</td>
                      <td>Mortuary</td>
                      <td>17</td>
                    </tr>
                    <tr>
                      <td>16</td>
                      <td>Faculty Block</td>
                      <td>82</td>
                    </tr>
                    <tr>
                      <td>17</td>
                      <td>Faculty of Education</td>
                      <td>130</td>
                    </tr>
                    <tr style="text-align: center;">
                      <td colspan="2"><strong>Total</strong></td>
                      <td><strong>1345</strong></td>
                    </tr>
                  </tbody>
                </table>
                <div class="row gutter-30 col-mb-5">
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s1.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Dental College Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s8.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer Hospital Roof</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s14.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Sub-Station No.3 Roof</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s2.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Engineering Block-I Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s9.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Indoor Stadium Roof</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s16.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Morchary 3 Roof</span>
                        </div>
                      </div>
                    </div>
                  </div>


                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s3.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Mala Bhawan Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s10.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> College of Nursing Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s16.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Faculty Block Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s4.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Medical College & Research Centre Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s12.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Vardhaman Bhawan Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s17.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Gyan Bhawan Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s5.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i>Prakash Bhawan Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s13.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Engineering Block-II Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s18.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Vidya Bhawan Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s6.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Pharmacy Block Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/s19.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Solar Panels</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Faculty of Education Block Roof </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Add the horizontal line here -->
              <hr class="horizontal-line">

              <button class="careers-accordion"> Biogas Plant<span class="icon">+</span></button>
              <div class="panel">
                <div class="row justify-content-center gutter-30 col-mb-5">
                  <div class="col-sm-8 col-md-8">
                    <p>The University has signed MoU with JARDS Moradabad, where biogas plant is situated. The students regularly visitthe plants for the exposer purpose.</p>
                  </div>
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/bio_gas.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">BioGas Plant </h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> TMU Campus</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <hr class="horizontal-line">

              <button class="careers-accordion"> Wheeling to the Grid<span class="icon">+</span></button>
              <div class="panel">
                <p>An <a href="https://www.tmu.ac.in/pdf/mous/wheeling_to_grid.pdf"> agreement</a> has been signed with Uttar Pradesh Power Corporation Limited (UPPCL) in regard with energy export to the grid and they provided net metering system to record the solar energy generation in campus.</p>
              </div>
              <hr class="horizontal-line">

              <button class="careers-accordion">Sensor-based Energy Conservation <span class="icon">+</span></button>
              <div class="panel">
                <p>TThe University has installed sensor based & wireless facility of conserve the energy at administrative block.</p>
                <div class="row gutter-30 col-mb-5">
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored1.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Sensor based Automatic Water Control System</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Ground Floor, Medical College & Research Centre</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored2.jpg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Sensor Based Energy Conservation </h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Indoor Stadium, Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="	https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored5.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Sensor Based Automatic Street Light System</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored3.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Sensor Based Energy Conservation Room</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Administrative Block, Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/sensored4.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Sensor Based Automatic Street Light System</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="horizontal-line">
              <button class="careers-accordion"> Use of LED Bulbs / Power-efficient Equipment<span class="icon">+</span></button>
              <div class="panel">
                <p>The University purchases only LED lights &replaced old tube light/ bulb from new LED lights as and when required presently 95% of the lights are LED. The updated &power saver equipmentlike fan, AC, fridge & other electronic items are replaced by five star rated equipment.</p>
                <div class="row gutter-30 col-mb-5">
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/led.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Uses of LED Bulbs</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/5_star/ac_1.jpeg" alt="">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">Uses of Power Efficient Equipments</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/led1.jpg" alt="" style="height:300px!important;">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">LED Street Light</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-4 col-md-4">
                    <div class="team card shadow-sm border-0 h-shadow h-translatey-sm all-ts rounded-4 overflow-hidden">
                      <div class="team-image">
                        <img src="https://www.tmu.ac.in/img/facilities/institutional_values/solar/led2.jpg" alt="" style="height:300px!important;">
                      </div>
                      <div class="team-desc p-2">
                        <div class="team-title pt-0">
                          <h4 class="fs-14">LED Street Light</h4><span class="fst-normal fs-12" style="font-size:16px; font-family:'poppins';"><i class="fa-solid fa-building"></i> Teerthanker Mahaveer University</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="horizontal-line">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section><!-- #content end -->


<?php
include 'footer.php';
?>